Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2020-10, with the labels that each got.

#253 PAY-3692 - Azure rm provider upgrade changes
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-253

#245 Refactoring Changes on DataLoss Report
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/ReportServiceImpl.java
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-245

#251 PAY-3147 - Added payment app for whitelisting
  src/main/resources/application.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-251

#256 PAY-3691: New vulnerabilities because of uk.gov.hmcts.java version 0.…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-256
