Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2020-05, with the labels that each got.

#200 Removed ASE Infrastructure
  config/owasp/suppressions.xml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, rel:ccpay-bulkscanning-api-pr-200

#205 Add Krishna thumbprint into perftest.tfvars
  config/owasp/suppressions.xml
  infrastructure/perftest.tfvars
Labels: ns:fees-pay, rel:ccpay-bulkscanning-api-pr-205

#208 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:fees-pay, rel:ccpay-bulkscanning-api-pr-208
