Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2020-11, with the labels that each got.

#263 supression added for tomcat-embed-core
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-263

#260 PAY-3704 - Terraform version upgrade to 0.13
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-260

#270 adding-new-exela-thumbprint
  infrastructure/prod.tfvars
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-270

#271 CVE-2020-15250 supression added
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-271

#268 PAY-3519 : DB Upgrade from v9.6 to v11 using 2nd approach
  charts/ccpay-bulkscanning-api/Chart.yaml
  charts/ccpay-bulkscanning-api/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
  src/functionalTest/resources/application-test.yaml
  src/test/resources/application-test.yaml
  src/test/resources/application.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-268
