Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2021-01, with the labels that each got.

#279 fix added for guava
  build.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-279

#276 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-276

#280 PAY-3919 : Removed the OLD DB instance mapping from main.tf
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-280

#272 Helm chart 3 upgrade changes
  build.gradle
  charts/ccpay-bulkscanning-api/Chart.yaml
  charts/ccpay-bulkscanning-api/requirements.yaml
  charts/ccpay-bulkscanning-api/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/SpringSecurityConfiguration.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-272

#283 Pay 3960 bulkscan cve fix
  build.gradle
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-283

#287 Pay 3960 bulkscan suppression limit extend
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-287
