Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2021-06, with the labels that each got.

#340 Nightly build spring core fix
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-340

#338 Pay 4029-OIDC-Deployment
  Jenkinsfile_CNP
  build.gradle
  charts/ccpay-bulkscanning-api/Chart.yaml
  charts/ccpay-bulkscanning-api/values.yaml
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  cve-resolution-strategy.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/config/IdamApi.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/config/IdamService.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
  src/functionalTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerServiceAndAnonymousUserFilter.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/authcheckerconfiguration/AuthCheckerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/converter/BSJwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/exception/BSAccessDeniedHandler.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/exception/BSAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/exception/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/filiters/ServiceAndUserAuthFilter.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/idam/IdamRepository.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/utils/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/validator/AudienceValidator.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/bulkscanning/BulkScanningApiApplicationTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/backdoors/RestActions.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/backdoors/ServiceResolverBackdoor.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/backdoors/UserResolverBackdoor.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/ComponentTestConfiguration.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/IdamApi.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/IdamService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/Oauth2.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/OneTimePasswordFactory.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/S2sApi.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/S2sTokenService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/SpringSecurityTestConfiguration.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/TestConfigProperties.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/User.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerServiceAndAnonymousUserFilterTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/security/converter/BSJwtGrantedAuthoritiesConverterTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/config/security/filiters/ServiceAndUserAuthFilterTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/ReportControllerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchControllerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/payments/ScannedChequeTester.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/ReportServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorTest.java
  src/test/resources/application-test.yaml
  src/test/resources/application.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-338

#343 audit.json refactored
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-343

#345 to keep-environment-specific-branches-in-sync-with-master
  Jenkinsfile_CNP
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-345
