Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2022-08, with the labels that each got.

#419 Fix fortify scan issue for username
  src/main/resources/application-local.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-419

#422 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-422

#425 Add backstage configuration file
  catalog-info.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-425
