Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2022-09, with the labels that each got.

#426 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-426

#424 PAY-5596 Ping 1 DCN
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
  src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchController.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/model/repository/PaymentMetadataRepository.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/model/repository/PaymentRepository.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentService.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/SearchService.java
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchControllerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceTest.java
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-424

#433 Update audit.json
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-433

#428 Update demo.tfvars
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-428, add-or-update

#430 update date in suppression file
  .gitignore
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-430

#432 adding config for new db
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, no-changes, rel:ccpay-bulkscanning-api-pr-432
