Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2022-02, with the labels that each got.

#398 cve fixes 14 feb 2022
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-398

#399 Update cve-resolution-strategy.gradle
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-399

#400 Update Chart.yaml
  charts/ccpay-bulkscanning-api/Chart.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-400
