Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2023-09, with the labels that each got.

#497 PAY-6510: Nightly build pipeline fixes
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-497

#498 PAY-6516: CVES
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-498

#502 PAY-6544: Renovate
  .github/renovate.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-502
