Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2023-10, with the labels that each got.

#500 PAY-6446: Update to fix exception record not being returned
  charts/ccpay-bulkscanning-api/Chart.yaml
  charts/ccpay-bulkscanning-api/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceTest.java
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-500, enable_keep_helm

#504 PAY-6572_Postgres-Migration for Demo
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-504

#505 PAY-6572_Postgres-Migration v15 for Demo
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-505

#506 PAY-6572_Postgres-Migration v15 for Demo removed public_access=true
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-506

#507 PAY-6572_Postgres-Migration v15 for Demo removed public_access=true
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-507

#512 Pay 6572 postgres migration
  config/owasp/suppressions.xml
  infrastructure/main.tf
  infrastructure/provider.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-512

#513 PAY-6572 amend extensions for flexible
  charts/ccpay-bulkscanning-api/Chart.yaml
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-bulkscanning-api-pr-513

#509 add version as suggested by fortify scan PAY-6608
  Dockerfile
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-509
