Repository hmcts/ccpay-bulkscanning-app, pull requests merged in 2024-02, with the labels that each got.

#528 PAY-6885 remove hardcoded password, which causes Fortify Scan failure
  src/main/resources/application-local.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-528

#529 PAY-6887- CVE 2023-34042 addressed
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-529

#530 PAY-6911: Pipeline analysis and resolution 26 February 2023
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bulkscanning-api-pr-530
